window.console||(window.console={log:function(){},error:function(){},debug:function(){}});
var polyClip=new function(){function s(c){D&&console.log(c)}function J(c,b){var e=new Image;jQuery(b).attr("data-polyclip-index",c);jQuery(e).bind("load",function(){var f=jQuery(b);f.attr("data-polyclip-transformorigin")||f.attr("data-polyclip-transformorigin",b.width/2+","+b.height/2);s("Cached "+e.src);A[e.src]=e;drawShape(c,b);var n,f=A,r=0;for(n in f)f.hasOwnProperty(n)&&r++;n=r;u.length==n?h.runCallbacks():s("Cached "+u.length+" out of "+n+" images.")});e.src=b.src}function t(c,b,e,f,n){c=c.x(b.add(e));
c=c.add(f);n.push(c.e(1));n.push(c.e(2));return c}var h=this,u,x=[],A=[],E=[],B=[],F=navigator.userAgent.match(/(iPad|iPhone|iPod)/i)?!0:!1;!F&&document.createElementNS&&document.createElementNS("http://www.w3.org/2000/svg","svg");var z,G,H,D=!1,I=!1;h.useSVGGlobally=!1;h.aniamtionNode=null;h.index=-1;h.isOldIE=window.G_vmlCanvasManager;h.polygonCache=[];h.init=function(){s("Initializing.");for(var c=document.getElementsByTagName("script"),b=null,e=0;e<c.length;e++){var f=c[e];f.src.match("polyclip(-p){0,1}.js")&&
(b=f)}if(!(c=!b)){var n=!1;jQuery.each(b.attributes,function(b,c){0==c.name.indexOf("data-")&&(n=!0)});c=!n}c&&(b=document.body);if(z=b)G=z.getAttribute("data-polyclip-clippreference"),H=z.getAttribute("data-polyclip-forcepointerevents"),D=z.getAttribute("data-polyclip-showdebugmessages")||!1,I=!h.isOldIE&&!F&&"true"==H,"SVG"==G&&I&&(h.useSVGGlobally=!0);h.$animationNode=jQuery('<div id="polyClip-tmp" />');document.body.appendChild(h.$animationNode.get(0));u=jQuery("img[data-polyclip]");s("Clipping "+
u.length+" image(s).");0<u.length?u.each(J):h.runCallbacks()};h.clipImage=function(c,b,e,f,n){var h=c.jquery?c:jQuery(c),j=b;f=h.attr("data-polyclip-transformorigin");var a,g;c=c.jquery?c.get(0):c;f&&(f=f.split(","));f&&2==f.length&&(a=parseFloat(f[0]),g=parseFloat(f[1]));!f||isNaN(a)||isNaN(g)?(f=c.offsetWidth/2,n=c.offsetHeight/2):(f=a,n=g);c.jquery&&c.get(0);if(e)if(window.$M){s(e);"string"==typeof e&&(e=C.getTransformationMatrix(e));c=e;g=f;j=n;a=jQuery.trim(b);g=null==g?0:g;j=null==j?0:j;b=$V([-g,
-j,0]);var j=$V([g,j,0]),l;if(0==a.indexOf("path:")){a=a.substring(5);g=a.replace(","," ").split(/\s+/);var d=[],p=$V([0,0,1]),k=null;for(a=0;a<g.length;){var m=g[a];isNaN(parseFloat(m))?d.push(m):(m=k,a--);var w=m.toUpperCase(),k=0;switch(w){case "M":case "L":case "T":k=1;break;case "S":case "Q":k=2;break;case "C":k=2}switch(w){case "H":l=$V([parseFloat(g[a+1]),p.e(2),1]);t(c,l,b,j,d);break;case "V":l=$V([p.e(1),parseFloat(g[a+1]),1]);t(c,l,b,j,d);break;case "M":case "L":case "T":case "S":case "Q":case "C":for(p=
0;p<k;p++)l=$V([parseFloat(g[a+2*p+1]),parseFloat(g[a+2*p+2]),1]),t(c,l,b,j,d);break;case "A":d.push(g[a+1],g[a+2],g[a+3],g[a+4],g[a+5]),l=$V([parseFloat(g[a+6]),parseFloat(g[a+7]),1]),t(c,l,b,j,d)}a+=1+2*k;k=m;p=l}j=void 0}else{g=[];d=a.split(",");for(a=0;a<d.length;a+=2)l=$V([parseInt(jQuery.trim(d[a])),parseInt(jQuery.trim(d[a+1])),1]),t(c,l,b,j,g);j=g.join(",")}s(e)}else s("Sylvester.js is needed for scaling clip. Transformation aborted.");h.attr("data-polyclip-transformcoords",j).attr("data-polyclip-transformorigin",
f+","+n).each(drawShape);return h};h.transformClip=function(c,b,e,f){c=c.jquery?c:jQuery(c);h.clipImage(c,c.attr("data-polyclip"),b,e,f)};drawShape=function(c,b){var e=jQuery(b),f=jQuery.trim(e.attr("data-polyclip")),n=jQuery.trim(e.attr("data-polyclip-transformcoords")),r=e.attr("data-polyclip-transformorigin").split(",");parseFloat(r[0]);parseFloat(r[1]);var j=n||f,a,g,l,d;a=b.src;var p,k=b.id?b.id:"polyClip"+c,m=e,w,s,u=h.useSVGGlobally||"SVG"==b.getAttribute("data-polyclip-clippreference")||"SVG"==
b.nodeName.toUpperCase(),v;p=[];if(0==j.indexOf("path:"))l=j.substr(5);else{g=j.split(",");for(j=0;j<g.length;j+=2){var t=parseInt(jQuery.trim(g[j])),y=parseInt(jQuery.trim(g[j+1]));p.push(t+","+y+" ")}}if(u||l)v='width="'+b.offsetWidth+'" height="'+b.offsetHeight+'"',v='<svg xmlns="http://www.w3.org/2000/svg" version="1.1" id="'+k+'" class="polyClip-clipped"  xmlns:xlink="http://www.w3.org/1999/xlink" '+v+'><defs><pattern id="polyClip-img-for-'+k+'" patternUnits="userSpaceOnUse" '+v+'><image xlink:href="'+
a+'" x="0" y="0" '+v+"/></pattern></defs>",v=l?v+('<path id="polyClip-poly-for-'+k+'" d="'+l+'" style="fill:url(\'#polyClip-img-for-'+k+"');\" /></svg>"):v+('<polygon id="polyClip-poly-for-'+k+'" points="'+p.join()+'" style="fill:url(\'#polyClip-img-for-'+k+"');\" /></svg>");switch(b.nodeName.toUpperCase()){case "IMG":w=b.offsetWidth;s=b.offsetHeight;if(u)w=(new DOMParser).parseFromString(v,"application/xml"),importNode=b.ownerDocument.importNode(w.documentElement,!0),e.attr("id","").replaceWith(importNode),
e=jQuery(importNode),e.attr("data-polyclip",f).attr("data-polyclip-transformcoords",n).attr("data-polyclip-transformorigin",r).attr("data-polyclip-transformoriginy",r),h.polygonCache[k]=jQuery("#polyClip-poly-for-"+k,e).get(0),w=b.offsetWidth,s=b.offsetHeight,m=e;else{var q=document.createElement("canvas"),m=jQuery(q);d=e.attr("data-polyclip-width");q.width=d?parseInt(d):w;d=e.attr("data-polyclip-height");q.height=d?parseInt(d):s;q.id=k;m.attr("data-polyclip",f).attr("data-polyclip-transformcoords",
n).attr("data-polyclip-transformorigin",r).attr("data-src",a).addClass("polyClip-clipped");e.replaceWith(q);h.isOldIE&&G_vmlCanvasManager.initElement(q);d=q.getContext("2d");E[k]=d;jQuery(window).trigger("resize");f=m.css("pointer-events");h.polygonCache[k]={ctx:d,imageData:d.getImageData?d.getImageData(0,0,q.width,q.height).data:null,pointerEventCSS:f?f.toLowerCase():null}}break;case "SVG":l?h.polygonCache[k].setAttribute("d",l):h.polygonCache[k].setAttribute("points",p.join());break;case "CANVAS":q=
b,a=e.attr("data-src"),d=E[k]}if(!u){x[q.id]=[];d.save();d.clearRect(0,0,q.width,q.height);if(l)d.drawSvg(v,0,0,w,s);else{d.beginPath();for(j=0;j<g.length;j+=2)t=parseInt(jQuery.trim(g[j])),y=parseInt(jQuery.trim(g[j+1])),x[q.id].push({x:t,y:y}),0==j?d.moveTo(t,y):d.lineTo(t,y);d.closePath()}h.isOldIE?(d.fillStyle="",d.fill(),g=jQuery("fill",q).get(0),l=jQuery("shape",q).get(0),g.color="none",l.fillcolor="none",g.src=a,g.type="tile",g.alignShape=!1):(a=d.createPattern(A[a],"repeat"),d.fillStyle=a,
d.fill());d.restore();f=m.css("pointer-events");h.polygonCache[k]={ctx:d,imageData:d.getImageData?d.getImageData(0,0,q.width,q.height).data:null,pointerEventCSS:f?f.toLowerCase():null}}return m};h.findObject=function(c){var b=c.currentTarget;if(jQuery(b).hasClass("cropParent"))return jQuery(b);for(var e in x)if(x.hasOwnProperty(e)&&(b=jQuery("#"+e),h.isInPolygon(b,c.pageX,c.pageY,!0)))return b};h.isInPolygon=function(c,b,e,f){var h=c.get(0),h=x[h.id],r=h.length,j,a,g,l,d,p,k=!1,m={left:0,top:0};f&&
(m=c.offset());if(3>r)return!1;j=h[r-1].x+m.left;a=h[r-1].y+m.top;for(p=0;p<r;p++)c=h[p].x+m.left,f=h[p].y+m.top,c>j?(g=j,d=c,l=a,a=f):(g=c,d=j,l=f),c<b==b<=j&&(e-l)*(d-g)<(a-l)*(b-g)&&(k=!k),j=c,a=f;return k};h.addCallback=function(c){B.push(c)};h.runCallbacks=function(){s("Cached all images.  Running callbacks...");for(var c=0;c<B.length;c++)B[c]()};if(window.$M)var C=new function(){function c(a){var b=parseFloat(a),c=a.match(e);"0"==a.trim()&&(b=0,c="rad");if(1!=c.length||0==b)return 0;c=c[0];
switch(c){case "deg":a=b*Math.PI/180;break;case "rad":a=b;break;default:throw"Not an angle: "+a;}return a}var b=this,e=/[a-z]+$/,f=/[a-zA-Z]+\([^\)]*\)\s*/g,h=/\(/g,r=/\)/g,j=/,/g;b.identity=$M([[1,0,0],[0,1,0],[0,0,1]]);b.prettyPrint=function(a){return StringHelpers.sprintf("| %s %s %s | - | %s %s %s | - |%s %s %s|",a.e(1,1),a.e(1,2),a.e(1,3),a.e(2,1),a.e(2,2),a.e(2,3),a.e(3,1),a.e(3,2),a.e(3,3))};b.rotate=function(a){a=c(a);return Matrix.RotationZ(a)};b.scale=function(a,b){a=parseFloat(a);b=b?parseFloat(b):
a;return $M([[a,0,0],[0,b,0],[0,0,1]])};b.scaleX=function(a){return b.scale(a,1)};b.scaleY=function(a){return b.scale(1,a)};b.skew=function(a,b){var f=c(a),d;d=null!=b?c(b):f;return null!=f&&null!=d?$M([[1,Math.tan(f),0],[Math.tan(d),1,0],[0,0,1]]):null};b.skewX=function(a){return b.skew(a,"0")};b.skewY=function(a){return b.skew("0",a)};b.translate=function(a,b){var c=parseInt(a),d=parseInt(b);return $M([[1,0,c],[0,1,d],[0,0,1]])};b.translateX=function(a){return b.translate(a,0)};b.translateY=function(a){return b.translate(0,
a)};b.matrix=function(a,b,c,d,f,e){return $M([[a,c,parseInt(f)],[b,d,parseInt(e)],[0,0,1]])};b.getTransformationMatrix=function(a,b){var c=a.match(f);if(b){var d=c.join(" ").replace(/\s*/g," "),e=a.replace(/\s*/g," ");if(d!=e)throw"An invalid transform was given: "+a;}for(var e=C.identity,k=0;k<c.length;k++){d=c[k];d=d.replace(h,'("').replace(j,'", "').replace(r,'")');try{var m=eval("MatrixGenerator."+d),e=e.x(m)}catch(s){if(b){c=d.split("(")[0];m=d.replace(/\"/g,"");if(void 0==C[c])throw"Error: invalid tranform function: "+
m;throw"Error: Invalid or missing parameters in function call: "+m;}}}return e}}};document.write('<style type="text/css">img[data-polyclip], img.polyClip { visibility: hidden; } </style>');polyClip.isOldIE?jQuery(window).bind("load",polyClip.init):jQuery(document).ready(polyClip.init);